services:
  cms:
    build:
      context: ./apps/cms
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: cms-db
      DATABASE_PORT: 5432
      DATABASE_NAME: cms-db
      DATABASE_USERNAME: cms-user
      DATABASE_PASSWORD: cms-password
    volumes:
      - cms-data:/var/lib/postgresql/data
    depends_on:
      - cms-db

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
      args:
        STRAPI_API_URL: http://cms:1337
    ports:
      - "8085:8787"
    env_file:
      - ./apps/frontend/.dev.vars
    environment:
      STRAPI_API_URL: http://cms:1337
      ASSISTANT_API_URL: http://localhost:8000/api
    depends_on:
      - cms
    develop:
      watch:
        - action: rebuild
          path: ./apps/frontend/.dev.vars
          target: /app/apps/frontend/.dev.vars

  cms-db:
    image: postgres
    environment:
      POSTGRES_USER: cms-user
      POSTGRES_PASSWORD: cms-password
      POSTGRES_DB: cms-db
    restart: always
    volumes:
      - cms-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  assistant:
    environment:
      FRONTEND_HOST: http://localhost:8085
    build:
      context: ./apps/assistant
      secrets:
        # Makes the secret file available to the build process
        - google_api_key
    ports:
      - "8000:8000"
    # env_file is still fine for non-sensitive runtime config
    # or for the final running container's key.
    env_file:
      - ./apps/assistant/.env

secrets:
  google_api_key:
    # Points to the file containing your secret key
    file: ./apps/assistant/.env

volumes:
  cms-data:
