name: Build and Deploy Frontend

on:
  push:
    branches: [chore/pm/astro]
  pull_request:
    branches: [chore/pm/astro]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  #     - name: Set up Deno
  #       uses: denoland/setup-deno@v2
  #       with:
  #         deno-version: v2.x

  #     - name: Install dependencies
  #       run: deno install --allow-scripts=npm:sharp@0.33.5,npm:workerd@1.20250507.0

  #     - name: Run build
  #       run: deno task frontend:build
  #       env:
  #         STRAPI_API_URL: ${{ secrets.STRAPI_API_URL }}
  #         STRAPI_API_TOKEN: ${{ secrets.STRAPI_API_TOKEN }}

      # - name: Upload build artifacts
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/chore/pm/astro' # Only upload on push to main
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-output
      #     path: ./apps/frontend/dist

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/chore/pm/astro' && needs.build.result == 'success'
    runs-on: ubuntu-latest
    steps:
      # - name: Download build artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: build-output
      #     path: ./apps/frontend/dist
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install --allow-scripts=npm:sharp@0.33.5,npm:workerd@1.20250507.0

      - name: Run build
        run: deno task frontend:build
        env:
          STRAPI_API_URL: ${{ secrets.STRAPI_API_URL }}
          STRAPI_API_TOKEN: ${{ secrets.STRAPI_API_TOKEN }}
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./apps/frontend
          wranglerVersion: '4.14.4'
          command: deploy